plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thuan.instafloat'
    compileSdk 35

    defaultConfig {
        applicationId 'com.thuan.instafloat'
        minSdk 26
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'org.jsoup:jsoup:1.18.3'
}
